# Generated by Django 4.2.3 on 2024-03-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('apple', 'Apple'), ('hp', 'Hewlett-Packard'), ('acer', 'Acer'), ('lenovo', 'Lenovo')], max_length=64, verbose_name='Бренд')),
                ('release_year', models.DateField(verbose_name='Бренд')),
                ('ram', models.PositiveSmallIntegerField(verbose_name='Объем ОЗУ')),
                ('hdd', models.PositiveSmallIntegerField(verbose_name='Объем HDD')),
                ('amount', models.FloatField(verbose_name='Цена')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество на складе')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Ноутбук',
                'verbose_name_plural': 'Ноутбуки',
                'ordering': ['-release_year'],
                'get_latest_by': 'release_year',
            },
        ),
    ]
