# Generated by Django 4.2.3 on 2024-03-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_alter_post_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('home', 'дом'), ('work', 'работа'), ('dev', 'разработка')], max_length=4, null=True, verbose_name='Категория'),
        ),
    ]
